### ISSUE TITLE
Having a better search

### ISSUE THREAD

**Issue by olielvewen** [nils-skowasch/soundblaster-x-g6-cli#1]
Hi,
I'm not owner of a Creative product but I would like to give you one advice. Because you have done a great work on your project.
I'm often on Github searching news and/or updating projects for linux hardware/devices. And I'm found by chance on your project. For a better search for potential users, you should had tags like creative, linux, soundblaster, x-g6 cli,.....
It will be easier for users.
Great work. Well done.
Bye.

**Comment by nils-skowasch** [comment]
Hey,
thank you for your message. I wasn't aware of that feature and added some topics to the project.
Best regards
